package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.38

import (
	"context"
	"fmt"

	"github.com/cclhsu/gin-graphql-gorm/graph/model"
)

// HealthCheck is the resolver for the HealthCheck field.
func (r *queryResolver) HealthCheck(ctx context.Context, request model.HealthRequestInput) (*model.HealthResponse, error) {
	panic(fmt.Errorf("not implemented: HealthCheck - HealthCheck"))
}
