package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.38

import (
	"context"
	"fmt"

	"github.com/cclhsu/gin-graphql-gorm/graph/model"
)

// GetHelloString is the resolver for the GetHelloString field.
func (r *queryResolver) GetHelloString(ctx context.Context) (string, error) {
	panic(fmt.Errorf("not implemented: GetHelloString - GetHelloString"))
}

// GetHelloJSON is the resolver for the GetHelloJson field.
func (r *queryResolver) GetHelloJSON(ctx context.Context) (*model.HelloJSONResponse, error) {
	panic(fmt.Errorf("not implemented: GetHelloJSON - GetHelloJson"))
}
